### ISSUE TITLE
Invalid Node fetch

### ISSUE THREAD

**Issue by sakurai8888** [microsoft/DiagManager#31]
I am connecting a clustered instance,
I used sql virtual network name already in the pssdiag.xml file. but still get 

2019/02/22 00:53:01.87 SQLDIAG Invalid node fetched. (null)

**Comment by PiJoCoder** [comment]
Invalid node fetched. error is raised when SQLDiag.exe is processing XML nodes. That's the invalid node referred to in the error.  But it is raised in a function that processes machine name and instance name. It has hard without any more data to determine the problem but possibly a mis-aligned pssdiag.xml (missing XML element or closing tag or something of the sort)
Otherwise, you can use the SQL Virtual network name just fine.
