### ISSUE TITLE
The latest build 13.0.1600.32 does not support SQL Server 2017

### ISSUE THREAD

**Issue by spacemandude** [microsoft/DiagManager#38]
Can Microsoft please release an updated DiagManager that can configure pssdiags for SQL Server 2017?  SQL 2019 is coming soon and it would be great if we can get that included in the next DiagManager release as well.

**Comment by xamarinOfCai** [comment]
+1

**Comment by billhol** [comment]
Due to backwards compatibility you can use most of the current DiagManger with 2017, and perhaps 2019. Extract pssd.zip and edit pssdiag.xml and search for "ssver", and save a backup copy of the file. Replace "ssver = '14'" with  "ssver = '*'" and save as pssdiag.xml. Upon running pssdiag.cmd you also may see one or two popup dialog warnings, about about not finding some processes, which I ignore. 

There are a couple of additional tweaks if you use SQL Nexus to digest pssdiag data: Choose Profiler Traces or Xevents, not both. And see Suresh' comment dated Jun 3, 2018 at https://github.com/Microsoft/SqlNexus/issues/49

**Comment by PiJoCoder** [comment]
The current couple of releases support up to 2019
