### ISSUE TITLE
Variable for SQL Server Log directory for error log files and extended events

### ISSUE THREAD

**Issue by YagneshDBA** [microsoft/DiagManager#50]
Hi,

I was using %SSPATH% variable before to get the location of the SQL Server log folder where we all the log files including extended event files are stored. Now it seems like not working. 

Could you please guide me which variable I should use to get the location of the log folder. I use that with ROBOCOPY command to copy all files created in last 7 days for my PSSDIag collection. Now that functionality is broken for my custom task. Could you please help me to resolve that.
-Yagnesh

**Comment by PiJoCoder** [comment]
@YagneshDBA, yes it appears that the SSPATH is failing, possibly reg key location was changed in newer versions. Since SSPATH is actually in [SQLDiag.exe](https://docs.microsoft.com/en-us/sql/tools/sqldiag-utility?view=sql-server-ver15), we can't contol in this project. One workaround would be to write your own custom collector in PowerShell for example and query the registry for the Log path.  (basically replacing what SQLDiag.exe is supposed to do)

```
$vInstance = "MSSQLSERVER"
$vRegInst = (Get-ItemProperty -Path HKLM:"SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\SQL").$vInstance
$vRegPath = "SOFTWARE\Microsoft\Microsoft SQL Server\" + $vRegInst + "\MSSQLServer\Parameters" 
(Get-ItemProperty -Path HKLM:$vRegPath).SQLArg1 -replace '-e', '' -replace 'ERRORLOG', ''
```
