### ISSUE TITLE
Always On Health/System Health XE files are not being collected

### ISSUE THREAD

**Issue by asavioli** [microsoft/DiagManager#72]
Version: internal

The Always On and system health extended event files are not being collect on almost all environments. The following error is showing on the command window (machine name replaced by xxx)

2021/05/20 11:11:44.83 xxxx\SQL2019 AlwaysOn Basic Info: AGConfig_Info
2021/05/20 11:11:46.29 xxxx\SQL2019 AlwaysOn Basic Info: AlwaysOnHealth_XEL
2021/05/20 11:11:46.29 xxxx\SQL2019 Error opening instance key . Instance: SQL2019. Function result: 2. Message: The system cannot find the file specified. 
2021/05/20 11:11:47.77 xxxx\SQL2019 MSInfo: MSINFO32

2021/05/20 11:11:56.83 xxxx\SQL2019 SQL Base: SQLDIAGXEL
2021/05/20 11:11:56.84 xxxx\SQL2019 Error opening instance key . Instance: SQL2019. Function result: 2. Message: The system cannot find the file specified. 
2021/05/20 11:11:58.38 xxxx\SQL2019 SQL Base: SystemHealthXEL
2021/05/20 11:11:58.39 xxxx\SQL2019 Error opening instance key . Instance: SQL2019. Function result: 2. Message: The system cannot find the file specified. 
2021/05/20 11:11:59.83 xxxx\SQL2019 SQL Base: TraceFlagHelperProcs

**Comment by PiJoCoder** [comment]
Looks like after initial investigation that the error:
"2021/05/20 11:11:56.83 xxxx\SQL2019 SQL Base: SQLDIAGXEL
2021/05/20 11:11:56.84 xxxx\SQL2019 Error opening instance key . Instance: SQL2019. Function result: 2. Message: The system cannot find the file specified."

... comes from SQLDiag.exe looking up a registry key to find the SQL Server path. And it is probably looking up the wrong reg key. One theory is that the reg key it was looking up has changed and that's why it is not able to find it. In any case, this is likely a SQLDiage.exe isssue, which means a SQL Server product group needs to investigate.

**Comment by asavioli** [comment]
Possibly this is the registry key SQLDiag is trying to search. There is no setup folder in it

![image](https://user-images.githubusercontent.com/49494532/163783490-2c6bfa25-b0d5-4e7c-b42b-f2cc4e9c9f0a.png)

**Comment by PiJoCoder** [comment]
> Possibly this is the registry key SQLDiag is trying to search. There is no setup folder in it
> 
> ![image](https://user-images.githubusercontent.com/49494532/163783490-2c6bfa25-b0d5-4e7c-b42b-f2cc4e9c9f0a.png)

It's possible, yes. The Wow portion is probably not accounted for, plus the instance name only (SQL2019) in this case should probably be MSSQL15.SQL2019 instead.

**Comment by PiJoCoder** [comment]
Seems like an issue with SQLDiag.exe, which we cannot control via PSSDIAG collector.
